#! /bin/sh

#### AUTOSTART ####

sxhkd &
picom &
feh --bg-fill ~/.config/.walls/nord.png &
~/.config/polybar/launch.sh &
setxkbmap -option caps:swapescape &

bspc monitor -d 1 2 3 4 5 

bspc config border_width                4
bspc config window_gap                  8
bspc config top_padding                 20
bspc config bottom_padding              0
bspc config left_padding                0
bspc config right_padding               0
bspc config single_monocle              false
bspc config focus_follows_pointer       true
bspc config focus_by_distance           true
bspc config history_aware_focus         true
bspc config remove_disabled_monitors    true
bspc config pointer_modifier            mod4
bspc config pointer_action1             move
bspc config pointer_action2             resize_side
bspc config pointer_action3             resize_corner
bspc config split_ratio                 0.50
bspc config borderless_monocle          true
bspc config gapless_monocle             true

#### colors ####
bspc config normal_border_color		    "#3b4252" 
bspc config active_border_color	        "#282c34" 
bspc config focused_border_color	    "#282c34"


#polybar hidden for vlc, youtube, mpv, etc
#xdo below -t $(xdo id -n root) $(xdo id -a polybar-main_DisplayPort-0)

bspc rule -a Gimp desktop='^8' state=floating follow=on
#bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
